name: Cloudflared
description: Install cloudflared tunnel CLI

inputs:
  version:
    description: 'Cloudflared version to install'
    required: false
    default: '2024.11.0'

runs:
  using: 'composite'
  steps:
    - name: Download cloudflared
      shell: bash
      run: |
        curl -L -o /tmp/cloudflared \
          "https://github.com/cloudflare/cloudflared/releases/download/${{ inputs.version }}/cloudflared-linux-amd64"
        chmod +x /tmp/cloudflared

    - name: Add to PATH
      shell: bash
      run: echo "/tmp" >> $GITHUB_PATH
