openapi: 3.0.3
info:
  title: CSV Export API
  description: API for exporting bills and accounts to CSV format
  version: 1.0.0

servers:
  - url: /api/v1
    description: Base API path (proxied via Next.js)

tags:
  - name: Export
    description: CSV export operations

paths:
  /export/bills:
    post:
      tags:
        - Export
      summary: Export bills to CSV
      description: |
        Generates and returns a CSV file containing journal entries (bills) based on optional filters.
        Returns streaming CSV response with UTF-8 BOM for Excel compatibility.
      operationId: exportBills
      parameters:
        - name: X-Tenant-ID
          in: header
          required: true
          schema:
            type: string
          description: Multi-tenant context
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportBillsRequest'
      responses:
        '200':
          description: CSV file stream
          content:
            text/csv:
              schema:
                type: string
                format: binary
              example: |
                Date,Description,Debit Account,Credit Account,Amount,Currency,Reference ID
                2024-01-15,Office supplies,Expenses:Office,Assets:Cash,150.50,USD,
                2024-01-16,Software subscription,Expenses:Software,Assets:Bank,299.00,USD,INV-2024-001
          headers:
            Content-Disposition:
              description: Attachment filename
              schema:
                type: string
                example: attachment; filename="bills-2024-01-23.csv"
            Content-Type:
              schema:
                type: string
                example: text/csv; charset=utf-8
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /export/accounts:
    post:
      tags:
        - Export
      summary: Export accounts to CSV
      description: |
        Generates and returns a CSV file containing account hierarchy based on optional filters.
        Returns streaming CSV response with UTF-8 BOM for Excel compatibility.
      operationId: exportAccounts
      parameters:
        - name: X-Tenant-ID
          in: header
          required: true
          schema:
            type: string
          description: Multi-tenant context
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportAccountsRequest'
      responses:
        '200':
          description: CSV file stream
          content:
            text/csv:
              schema:
                type: string
                format: binary
              example: |
                Account Name,Account Type,Parent Account,Currency,Balance,Is Active,Depth
                Assets,assets,,USD,0.00,true,0
                Assets:Cash,assets,Assets,USD,5000.00,true,1
                Assets:Bank,assets,Assets,USD,15000.00,true,1
                Expenses,expenses,,USD,0.00,true,0
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /export/status/{exportId}:
    get:
      tags:
        - Export
      summary: Get export status
      description: Returns the status of an export request for long-running exports
      operationId: getExportStatus
      parameters:
        - name: exportId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Export request ID
        - name: X-Tenant-ID
          in: header
          required: true
          schema:
            type: string
          description: Multi-tenant context
      responses:
        '200':
          description: Export status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportStatusResponse'
        '404':
          description: Export not found

components:
  schemas:
    ExportBillsRequest:
      type: object
      properties:
        date_from:
          type: string
          format: date
          description: Start date (ISO 8601 format)
          example: "2024-01-01"
        date_to:
          type: string
          format: date
          description: End date (ISO 8601 format)
          example: "2024-01-31"
        date_preset:
          type: string
          enum:
            - last_30_days
            - last_90_days
            - this_year
            - all_time
          description: Preset date range (mutually exclusive with date_from/date_to)
          example: "last_30_days"
        account_types:
          type: array
          items:
            type: string
            enum:
              - assets
              - liabilities
              - equity
              - revenue
              - expense
          description: Filter by account types involved in transactions
          example: ["assets", "expense"]
        include_header:
          type: boolean
          default: true
          description: Include column headers in output
        delimiter:
          type: string
          enum:
            - ','
            - ';'
            - '\t'
          default: ','
          description: CSV delimiter character
      description: Request body for bills export
      example:
        date_preset: "last_30_days"
        account_types: ["assets", "expense"]
        delimiter: ","

    ExportAccountsRequest:
      type: object
      properties:
        account_types:
          type: array
          items:
            type: string
            enum:
              - assets
              - liabilities
              - equity
              - revenue
              - expense
          description: Filter by account types
          example: ["assets", "liability"]
        include_inactive:
          type: boolean
          default: false
          description: Include inactive accounts
        include_header:
          type: boolean
          default: true
          description: Include column headers in output
        delimiter:
          type: string
          enum:
            - ','
            - ';'
            - '\t'
          default: ','
          description: CSV delimiter character
      description: Request body for accounts export
      example:
        account_types: ["assets"]
        include_inactive: false
        delimiter: ","

    ExportStatusResponse:
      type: object
      properties:
        export_id:
          type: string
          format: uuid
          description: Export request ID
        status:
          type: string
          enum:
            - pending
            - processing
            - completed
            - failed
          description: Current export status
        progress:
          type: number
          format: float
          description: Progress percentage (0-100)
          example: 45.5
        record_count:
          type: integer
          description: Number of records processed so far
          example: 4500
        total_records:
          type: integer
          description: Total estimated records
          example: 10000
        download_url:
          type: string
          description: URL to download completed export (valid for 1 hour)
          nullable: true
        error_message:
          type: string
          description: Error details if failed
          nullable: true
        created_at:
          type: string
          format: date-time
          description: When export was requested
      example:
        export_id: "550e8400-e29b-41d4-a716-446655440000"
        status: "processing"
        progress: 45.5
        record_count: 4500
        total_records: 10000
        download_url: null
        error_message: null
        created_at: "2024-01-23T10:00:00Z"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error_code:
          type: string
          example: "INVALID_DATE_RANGE"
        error_message:
          type: string
          example: "date_from must be before or equal to date_to"
        details:
          type: object
          description: Additional error details
      example:
        success: false
        error_code: "INVALID_DATE_RANGE"
        error_message: "date_from must be before or equal to date_to"
        details:
          date_from: "2024-01-31"
          date_to: "2024-01-01"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token authentication via Authorization header

security:
  - bearerAuth: []
